/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContent: typeof import('./src/components/AppContent.vue')['default']
    BalanceCard: typeof import('./src/components/user/BalanceCard.vue')['default']
    HomeMenu: typeof import('./src/components/HomeMenu.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NFlex: typeof import('naive-ui')['NFlex']
    NG: typeof import('naive-ui')['NG']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTextarea: typeof import('naive-ui')['NTextarea']
    NUpload: typeof import('naive-ui')['NUpload']
    NWaterfall: typeof import('naive-ui')['NWaterfall']
    ProductCard: typeof import('./src/components/productCard.vue')['default']
    RechargeForm: typeof import('./src/components/user/rechargeForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    Traffic: typeof import('./src/components/Traffic.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    WithdarwHistory: typeof import('./src/components/user/withdarwHistory.vue')['default']
    WithdrawForm: typeof import('./src/components/user/withdrawForm.vue')['default']
  }
}
